# Generated by Django 4.0.3 on 2022-03-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
    ]
