# Generated by Django 4.0.3 on 2022-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
