# Generated by Django 4.0.3 on 2022-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
