# Generated by Django 4.0.3 on 2022-03-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_participant_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['id']},
        ),
    ]
