# Generated by Django 4.0.3 on 2022-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_participant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
