# Generated by Django 4.0.3 on 2022-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('participants', models.ManyToManyField(to='participants.participant')),
            ],
            options={
                'ordering': ['start_time', 'end_time'],
            },
        ),
    ]
