# Generated by Django 4.0.3 on 2022-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
